package Vgu.tests;

import VGU.Pages.VGUHomePage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.testng.annotations.Test;



public class Vgutest  extends BaseTest{
    private static final Logger log = LoggerFactory.getLogger(Vgutest.class);
    VGUHomePage homePage = null;

 //@Test(priority = 1, description = "Testing Login")
  public void VguTest() {
      homePage = new VGUHomePage(driver);
      driver.get(URL);
      logger.info("VGU Login Page");
      homePage.enterEmail();
      logger.info("Email entered");
      homePage.enterPassword();
      logger.info("Password entered");
      homePage.clickLogin();
      logger.info("Clicked Login");
      homePage.clickLogout();
      logger.info("Clicked Logout");
  }
// @Test(priority = 2, description = "Verify Navigation")
      public void VguTest1() {
      homePage = new VGUHomePage(driver);
      driver.get(URL);
      logger.info("VGU Login Page");
      homePage.enterEmail();
      logger.info("Email entered");
      homePage.enterPassword();
      logger.info("Password entered");
      homePage.clickLogin();
      logger.info("Clicked Login");
      homePage.clickDashboard();
      logger.info("Clicked Dashboard");
      homePage.clickDiscussion();
      logger.info("Clicked Discussion");
      homePage.clickVirtualClass();
      logger.info("Clicked Virtual Class");
      homePage.clickCourse();
      logger.info("Clicked Course");
      homePage.clickProgram();
      logger.info("Clicked Program");
      homePage.clickRoleManagement();
      logger.info("Clicked Role Management");
      homePage.clickExamination();
      logger.info("Clicked Examination");
      homePage.clickUserManagement();
      logger.info("Clicked User Management");
      homePage.clickFeemanagement();
      logger.info("Clicked Fee Management");
      homePage.clickReportManagement();
      logger.info("Clicked Report Management");
      homePage.clickRequestManagement();
      logger.info("Clicked Request Management");
      homePage.clickAnnouncement();
      logger.info("Clicked Announcement");
      homePage.clickAddons();
      logger.info("Clicked Addons");
      homePage.clickLogout();
      logger.info("Clicked Logout");
      }

 // @Test(priority = 3, description="Create Virtual Class")
    public void VguTest2(){
      homePage = new VGUHomePage(driver);
      driver.get(URL);
      logger.info("Entered VGU Login Page");
      homePage.enterEmail();
      logger.info("Entered Email");
      homePage.enterPassword();
      logger.info("Entered Password");
      homePage.clickLogin();
      logger.info("Clicked on Login");
      homePage.clickVirtualClass();
      logger.info("Clicked on Virtual Class Tab");
      homePage.ClickCreate();
      logger.info("Clicked on Create New Class Button");
      homePage.enterMeetingName();
      logger.info("Entered Virtual Class Title");
      homePage.clickOnClassSelectDropdown();
      logger.info("Clicked on Course Dropdown");
      homePage.selectCourse();
      logger.info("Selected Course");
      homePage.clickOnFacultyDropdown();
      logger.info("Clicked on Faculty Dropdown");
      homePage.selectFaculty();
      logger.info("Selected Faculty");
      homePage.clickCalendar();
      logger.info("Clicked on Calendar Button");
      homePage.selectDate();
      logger.info("Selected Date");
      homePage.clickStartTime();
      logger.info("Clicked on Start Time");
      homePage.selectStartHour();
      logger.info("Entered Start Hour");
      homePage.selectStartMinute();
      logger.info("Entered StartHour Minutes");
      homePage.chooseAmPM();
      logger.info("Selected PM");
      homePage.clickEndTime();
      logger.info("Clicked on End Time");
      homePage.selectEndHour();
      logger.info("Entered End Hour");
      homePage.selectEndMin();
      logger.info("Entered EndHour Minutes");
      homePage.selectPM();
      logger.info("Selected PM");
      homePage.enterMeetingLink();
      logger.info("Entered Meeting Link");
      homePage.enterZoomUserName();
      logger.info("Entered Zoom User Name");
      homePage.clickPublishButton();
      logger.info("Clicked on Publish Button");
      homePage.clickYesInPopUp();
      logger.info("Clicked on Yes in PopUp");

  }
// @Test(priority = 4, description = "CreateCourse")
    public void VguTest3(){
      homePage = new VGUHomePage(driver);
      driver.get(URL);
      logger.info("Entered VGU Login Page");
      homePage.enterEmail();
      logger.info("Entered Email Address");
      homePage.enterPassword();
      logger.info("Entered Password");
      homePage.clickLogin();
      logger.info("Clicked on Login Button");
      homePage.clickCourse();
      logger.info("Clicked on Course Tab");
      homePage.clickCreateCourse();
      logger.info("Clicked on Create New Course Button");
      homePage.enterCourseTitle();
      logger.info("Entered Course Title");
      homePage.enterCourseCode();
      logger.info("Entered Course Code");
      homePage.facultyDropdown();
      logger.info("Clicked on Faculty Dropdown");
      homePage.selectFacultyOption();
      logger.info("Selected Faculty");
      homePage.enterCourseCredit();
      logger.info("Entered Course Credits");
      homePage.enterCourseDescription();
      logger.info("Entered Course Description");
      homePage.uploadPreviewImage();
      logger.info("Uploaded Course Preview Image");
      homePage.clickSave();
      logger.info("Clicked on Save Button");
      homePage.clickAddChapter();
      logger.info("Clicked on Add New Chapter Button");
      homePage.clickOnChapter();
      logger.info("Clicked on Chapter Tab");
      homePage.enterChapterTitle();
      logger.info("Entered Chapter Title");
      homePage.clickSave();
      logger.info("Clicked on Save Button");
      homePage.clickAddTopic();
      logger.info("Clicked on Add Topic Button");
      homePage.clickOnTopic();
      logger.info("Clicked on Topic Tab");
      homePage.enterTopicTitle();
      logger.info("Entered Topic Title");
      homePage.uploadTopicVideo();
      logger.info("Uploaded Topic Video");
      homePage.enterReferenceName();
      logger.info("Entered Reference Name");
      homePage.enterReferenceLink();
      logger.info("Entered Reference Link");
      homePage.SaveCourse();
      logger.info("Clicked On Save Course");
      homePage.clickPublishCourse();
      logger.info("Clicked on Publish Course");
      homePage.clickYesPopUp();
      logger.info("Clicked on Yes in the PopUp");
  }
 //@Test(priority = 5, description = "Testing Program Creation")
  public void VguTest4(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked On Login");
    homePage.clickProgram();
    logger.info("Clicked on Program Tab");
    homePage.clickCreateNewProgram();
    logger.info("Clicked on Create New Program Button");
    homePage.enterProgramName();
    logger.info("Entered Program Name");
    homePage.semesterDropdown();
    logger.info("Clicked on Semester Dropdown");
    homePage.selectSemester();
    logger.info("Selected Semester");
    homePage.facultyDrop();
    logger.info("Clicked On Faculty Dropdown");
    homePage.selectFacultyFromDropdown();
    logger.info("Selected Faculty");
    homePage.programCoordinatorDropdown();
    logger.info("Clicked on Program Coordinator Dropdown");
    homePage.selectProgramCoordinator();
    logger.info("Selected Program Coordinator");
    homePage.programTypeDropdown();
    logger.info("Clicked on Program Type Dropdown");
    homePage.selectProgramType();
    logger.info("Selected Program Type");
    homePage.enterProgramCode();
    logger.info("Entered Program Code");
    homePage.enterProgramOverview();
    logger.info("Entered Program Overview");
    homePage.clickPublishCourse();
    logger.info("Clicked on Publish Program");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
 // @Test(priority = 6, description = "Testing AddNewStaff User")
  public void VguTest5(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU HomePage");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickUserManagement();
    logger.info("Clicked on UserManagement Tab");
    homePage.clickAddNewStaff();
    logger.info("Clicked on Add New Staff Button");
    homePage.enterStaffName();
    logger.info("Entered Staff Name");
    homePage.enterMobileNumber();
    logger.info("Entered Mobile Number");
    homePage.enterStaffEmail();
    logger.info("Entered Staff Email");
    homePage.clickOnRoleDropdown();
    logger.info("Clicked on Role Dropdown");
    homePage.selectRole();
    logger.info("Selected Role");
    homePage.clickOnCalendar();
    logger.info("Clicked on Calendar");
    homePage.selectJoiningDate();
    logger.info("Selected Joining Date");
    homePage.clickSubmitButton();
    logger.info("Clicked on Submit Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 7, description = "Testing Student Upload in UserManagement")
  public void VguTest6(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickUserManagement();
    logger.info("Clicked on UserManagement Tab");
    homePage.clickStudentTab();
    logger.info("Clicked on Student Tab");
    homePage.clickAddNewStudent();
    logger.info("Clicked on Add New Student Button");
    homePage.enterStudentName();
    logger.info("Entered Student Name");
    homePage.enterFatherName();
    logger.info("Entered Father Name");
    homePage.enterMotherName();
    logger.info("Entered Mother Name");
    homePage.enterStudentMobileNum();
    logger.info("Entered Student Mobile Number");
    homePage.clickOnLocal();
    logger.info("Clicked Locality Dropdown");
    homePage.selectLocality();
    logger.info("Selected Locality");
    homePage.enterStudentEmail();
    logger.info("Entered Student Email");
    homePage.clickOnTypeDropdown();
    logger.info("Clicked on Student Type Dropdown");
    homePage.selectStudentType();
    logger.info("Selected Student Type");
    homePage.clickStudentCategoryDropdown();
    logger.info("Clicked on Category Dropdown");
    homePage.selectStudentCategory();
    logger.info("Selected Student Category");
    homePage.enterStudentMarks();
    logger.info("Entered Student Marks");
    homePage.clickonFacultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectOnFacultyOption();
    logger.info("Selected Faculty");
    homePage.clickonProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatchDropdown();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickAdmissionDropdown();
    logger.info("Clicked on Admission Dropdown");
    homePage.selectAdmissionOption();
    logger.info("Selected Admission Type");
    homePage.enterStudentAdmissionDate();
    logger.info("Entered Admission Date");
    homePage.clickOnGovtIdentifierDropdown();
    logger.info("Clicked on Govt Identifier Dropdown");
    homePage.selectGovtIdentifierOption();
    logger.info("Selected Govt Identifier Option");
    homePage.enterGovtId();
    logger.info("Entered Govt ID");
    homePage.clickSubmitButton();
    logger.info("Clicked on Submit Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 8, description = "Test Bulk Upload of Students")
  public void VguTest7(){
    homePage= new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickUserManagement();
    logger.info("Clicked on UserManagement Tab");
    homePage.clickStudentTab();
    logger.info("Clicked on Student Tab");
    homePage.clickBulkUploadButton();
    logger.info("Clicked on BulkUpload Button");
    homePage.clickonFacultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectOnFacultyOption();
    logger.info("Selected Faculty");
    homePage.clickProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickOnTypeDropdown();
    logger.info("Clicked on Student Type Dropdown");
    homePage.selectStudentType();
    logger.info("Selected Student Type");
    homePage.bulkUploadFile();
    logger.info("Uploaded Bulk Student Upload File");
    homePage.clickAutoGenerateRollNo();
    logger.info("Clicked on AutoGenerate Roll No Button");
    homePage.clickAddButton();
    logger.info("Clicked on Add Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 9, description = "Testing StaffBulkUpload")
  public void VguTest8(){
    homePage=new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickUserManagement();
    logger.info("Clicked on UserManagement Tab");
    homePage.clickStaffBulkButton();
    logger.info("Clicked on Staff Bulk Upload Button");
    homePage.bulkUploadStaff();
    logger.info("Uploaded Staff Bulk Upload File");
    homePage.clickAddButton();
    logger.info("Clicked on Add Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 10, description = "Testing Discussion Creation")
  public void VguTest9(){
    homePage=new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickDiscussion();
    logger.info("Clicked on Discussion Tab");
    homePage.clickCreateDiscussion();
    logger.info("Clicked on Create Discussion Button");
    homePage.enterDiscussionTitle();
    logger.info("Entered Discussion Title");
    homePage.clickOnFacultyDrop();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyName();
    logger.info("Selected Faculty");
    homePage.clickOnProgarmDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramName();
    logger.info("Selected Program");
    homePage.clickOnCourseDropdown();
    logger.info("Clicked on Course Dropdown");
    homePage.selectCourseName();
    logger.info("Selected Course");
    homePage.clickOnCategoryDropdown();
    logger.info("Clicked on Category Dropdown");
    homePage.selectCategory();
    logger.info("Selected Category");
    homePage.clickOnBatchDropdown();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatch();
    logger.info("Selected Batch");
    homePage.enterDescription();
    logger.info("Entered Description");
    homePage.clickCreate();
    logger.info("Clicked on Create Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
 // @Test(priority = 11,description = "Testing Marks Upload")
  public void VguTest10(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickOnGradeReport();
    logger.info("Clicked on Grade Report");
    homePage.clickUploadMarksButton();
    logger.info("Clicked Upload Marks Button");
    homePage.clickAcademicYearDropdown();
    logger.info("Clicked on Academic Year Dropdown");
    homePage.selectAcademicYear();
    logger.info("Selected Academic Year");
    homePage.clickAcademicMonthDropdown();
    logger.info("Clicked on Academic Month Dropdown");
    homePage.selectAcademicMonth();
    logger.info("Selected Academic Month");
    homePage.clickFacultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyInDropdown();
    logger.info("Selected Faculty");
    homePage.clickonProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickExamSessionDropdown();
    logger.info("Clicked on Exam Session Dropdown");
    homePage.selectExamSession();
    logger.info("Selected Exam Session");
    homePage.selectInternalOption();
    logger.info("Selected Internal Option");
    homePage.UploadInternalMarks();
    logger.info("Uploaded Internal Marks");
    homePage.clickSubmitButton();
    logger.info("Clicked Submit Button");
  }
 //@Test(priority = 12,description = "Testing External Marks Upload")
  public void VguTest11() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickOnGradeReport();
    logger.info("Clicked on Grade Report");
    homePage.clickUploadMarksButton();
    logger.info("Clicked Upload Marks Button");
    homePage.clickAcademicYearDropdown();
    logger.info("Clicked on Academic Year Dropdown");
    homePage.selectAcademicYear();
    logger.info("Selected Academic Year");
    homePage.clickAcademicMonthDropdown();
    logger.info("Clicked on Academic Month Dropdown");
    homePage.selectAcademicMonth();
    logger.info("Selected Academic Month");
    homePage.clickFacultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyInDropdown();
    logger.info("Selected Faculty");
    homePage.clickonProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickExamSessionDropdown();
    logger.info("Clicked on Exam Session Dropdown");
    homePage.selectExamSession();
    logger.info("Selected Exam Session");
    homePage.selectExternalOption();
    logger.info("Selected External Option");
    homePage.UploadExternalMarks();
    logger.info("Uploaded External Marks");
    homePage.clickSubmitButton();
    logger.info("Clicked Submitted Button");
  }
  //@Test(priority = 13,description = "Testing Batch Creation")
  public void VguTest12(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickProgram();
    logger.info("Clicked on Program Tab");
    homePage.clickOnProgram();
    logger.info("Clicked on BA Program");
    homePage.clickOnBatch();
    logger.info("Clicked on Batch Tab");
    homePage.clickOnCreateBatchButton();
    logger.info("Clicked on Create New Batch Button");
    homePage.clickOnSemesterDropdown();
    logger.info("Clicked on Semester Dropdown");
    homePage.selectSemesterFromDropdown();
    logger.info("Selected Semester Number");
    homePage.clickOnAcademicYearDropdown();
    logger.info("Clicked on Academic Year Dropdown");
    homePage.selectAcademicYearFromDropdown();
    logger.info("Selected Academic Year");
    homePage.clickOnAcademicSessionDropdown();
    logger.info("Clicked on Academic Session Dropdown");
    homePage.selectAcademicSessionFromDropdown();
    logger.info("Selected Academic Session");
    homePage.EnterBatchName();
    logger.info("Entered Batch Name");
    homePage.clickOnSpecializationDropdown();
    logger.info("Clicked on Specialization Dropdown");
    homePage.selectSpecialization();
    logger.info("Selected Specialization");
    homePage.enterDescriptionOfBatch();
    logger.info("Entered Description");
    homePage.clickCreate();
    logger.info("Clicked Create");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
 //@Test(priority = 14,description = "Testing Assigning Course Coordinator")
  public void VguTest13(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickProgram();
    logger.info("Clicked on Program Tab");
    homePage.clickOnProgram();
    logger.info("Clicked on BA Program");
    homePage.clickOnBatch();
    logger.info("Clicked on Batch Tab");
    homePage.clickOnBatchTab();
    logger.info("Clicked on Batch");
    homePage.clickOnCourse();
    logger.info("Clicked On Course");
    homePage.clickOnAssignCourseCoordinator();
    logger.info("Clicked on Assign Course Coordinator");
    homePage.clickOnCourseCoordinatorDropdown();
    logger.info("Clicked on Course Coordinator Dropdown");
    homePage.selectCourseCoordinator();
    logger.info("Selected Course Coordinator");
    homePage.clickAssign();
    logger.info("Clicked on Assign");
  }

  //@Test(priority = 15,description = "Testing Announcement Creation")
  public void VguTest14(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickAnnouncement();
    logger.info("Clicked on Announcement");
    homePage.clickCreateNewAnnouncement();
    logger.info("Clicked on Create New Announcement");
    homePage.enterAnnouncementTitle();
    logger.info("Entered Announcement Title");
    homePage.enterAnnouncementDescription();
    logger.info("Entered Announcement Description");
    homePage.clickEventCalendar();
    logger.info("Clicked on Event Calendar");
    homePage.selectEventDate();
    logger.info("Selected Event Date");
    homePage.enterEventTimeHour();
    logger.info("Enter Event Time Hour");
    homePage.enterEventTimeMin();
    logger.info("Enter Event Time Minute");
    homePage.selectAm();
    logger.info("Selected AM");
    homePage.clickOnEventTypeDropdown();
    logger.info("Clicked on Event Type Dropdown");
    homePage.selectEventType();
    logger.info("Selected Event Type");
    homePage.selectEveryoneRecipient();
    logger.info("Selected Everyone Recipient");
    homePage.clickFacultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyDropdown();
    logger.info("Selected Faculty");
    homePage.selectEveryoneRecipient();
    homePage.clickProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramDropdown();
    logger.info("Selected Program");
    homePage.selectEveryoneRecipient();
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchDropdown();
    logger.info("Selected Batch");
    homePage.selectEveryoneRecipient();
    homePage.selectEveryoneRecipient();
    homePage.clickPublishButton();
    logger.info("Clicked Publish Button");
    homePage.clickYesInPopUp();
    logger.info("Clicked Yes in the Popup");
  }
  //@Test(priority = 16,description = "Testing Exam Creation")
  public void VguTest15(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickExamination();
    logger.info("Clicked on Exam Tab");
    homePage.clickCreateNewExamSession();
    logger.info("Clicked On Created New Session Button");
    homePage.enterExamsSessionName();
    logger.info("Entered Exam Session Name");
    homePage.enterExamSessionCode();
    logger.info("Entered Exam Session Code");
    homePage.clickOnStartDateCalendar();
    logger.info("Clicked on Start Date Calendar");
    homePage.clickNextMonth();
    logger.info("Clicked on Next Month Button");
    homePage.selectStartDate();
    logger.info("Selected Start Date");
    homePage.clickEndDateCalendar();
    logger.info("Clicked on End Date Calendar");
    homePage.clickNextMonthEndDate();
    logger.info("CLicked on Next Month Button");
    homePage.selectEndDate();
    logger.info("Selected End Date");
    homePage.removeBASFaculty();
    logger.info("Removed BAS Faculty");
    homePage.removeCAFaculty();
    logger.info("Removed CA Faculty");
    homePage.removeBAProgram();
    logger.info("Removed BA Program");
    homePage.selectMonday();
    logger.info("Selected Monday");
    homePage.selectWednesday();
    logger.info("Selected Wednesday");
    homePage.selectFriday();
    logger.info("Selected Friday");
    homePage.enterExamDuration();
    logger.info("Entered Exam Duration");
    homePage.clickStartSlotTime();
    logger.info("Clicked on Select Slot Time");
    homePage.enterHourStartSlot1();
    logger.info("Entered Slot 1 Hour");
    homePage.enterMinStartSlot1();
    logger.info("Entered Slot 1 Mins");
    homePage.selectAM();
    logger.info("Selected AM");
    homePage.clickAddSlot();
    logger.info("Clicked on Add Slot Button");
    homePage.clickStartTime2();
    logger.info("Clicked on Select Slot Time");
    homePage.enterHourSlotTime2();
    logger.info("Entered Slot 2 Hour");
    homePage.enterMinSlotTime2();
    logger.info("Entered Slot 2 Mins");
    homePage.selectAM2();
    logger.info("Selected AM");
    homePage.clickNextButton();
    logger.info("Clicked on Next Month");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the PopUp");
    homePage.clickPublishButton();
    logger.info("Clicked on Publish");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
 // @Test(priority = 17,description = "Testing Upload ID card Picture")
  public void VguTest16(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickUserManagement();
    logger.info("Clicked on UserManagement Tab");
    homePage.clickStudentTab();
    logger.info("Clicked on Student Tab");
    homePage.clickViewIcon();
    logger.info("Clicked on View Icon Button");
    homePage.clickUploadIDCardButton();
    logger.info("Clicked on Upload ID Card Button");
    homePage.UploadIDPic();
    logger.info("Uploaded ID Card Picture");
    homePage.clickConfirmButton();
    logger.info("Clicked on Confirm Button");
  }
 // @Test(priority = 18,description = "Student Requesting for E ID card")
  public void VguTest17(){
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.studentEmailID();
    logger.info("Entered Email Address");
    homePage.studentPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login");
    homePage.clickOnRequestModule();
    logger.info("Clicked on Request Management");
    homePage.clickNewRequestButton();
    logger.info("Clicked on New Request Button");
    homePage.clickOnRequestTypeDropdown();
    logger.info("Clicked on Request Type dropdown");
    homePage.selectRequestType();
    logger.info("Selected Request Type");
    homePage.enterRequestDescription();
    logger.info("Entered Description");
    homePage.AttachPicture();
    logger.info("Uploaded Picture");
    homePage.clickRequestButton();
    logger.info("Clicked on Request Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
 // @Test(priority = 19,description = "Admin Approving Request")
  public void VguTest18() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickRequestManagement();
    logger.info("Clicked on Request Management");
    homePage.clickViewRequest();
    logger.info("Clicked on Request View Button");
    homePage.enterApproverComments();
    logger.info("Entered Approver Comments");
    homePage.clickApproveButton();
    logger.info("Clicked on Approve Button");
    homePage.clickYesPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 20,description = "Assigning Course to a batch")
  public void VguTest19() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickCourse();
    logger.info("Clicked on Course");
    homePage.clickPublishedCourses();
    logger.info("Clicked on Published Courses");
    homePage.clickAssignCourse();
    logger.info("Clicked on Assign course");
    homePage.clickProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickAssignButton();
    logger.info("Clicked On Assign Button");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the popup");
  }
 // @Test(priority = 21,description = "UnAssigning Course from a batch")
  public void VguTest20() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickCourse();
    logger.info("Clicked on Course");
    homePage.clickPublishedCourses();
    logger.info("Clicked on Published Courses");
    homePage.clickUnassignCourse();
    logger.info("Clicked on UnassignCourse");
    homePage.clickRemoveBatch();
    logger.info("Batch Removed");
    homePage.clickSave();
    logger.info("Clicked on Save Button");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the popup");
  }
 // @Test(priority = 22,description = "Testing Unpublishing Course")
  public void VguTest21() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickCourse();
    logger.info("Clicked on Course");
    homePage.clickPublishedCourses();
    logger.info("Clicked on Published Courses");
    homePage.clickUnPublishCourse();
    logger.info("Clicked on Unpublish Course");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 23,description = "Uploading Fee Details")
  public void VguTest22() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickFeemanagement();
    logger.info("Clicked on Fee Management");
    homePage.clickFeeUploadButton();
    logger.info("Click on Upload Fee Button");
    homePage.facultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyOption();
    logger.info("Selected Faculty Option");
    homePage.clickProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickUploadButton();
    logger.info("Uploaded Fee details");
    homePage.clickAddButton();
    logger.info("Clicked on Add Button");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
//  @Test(priority = 24,description = "Uploading Fee Transactions")
  public void VguTest23() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.enterEmail();
    logger.info("Entered Email");
    homePage.enterPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login Button");
    homePage.clickFeemanagement();
    logger.info("Clicked on Fee Management");
    homePage.clickFeeUploadButton();
    logger.info("Click on Upload Fee Button");
    homePage.facultyDropdown();
    logger.info("Clicked on Faculty Dropdown");
    homePage.selectFacultyOption();
    logger.info("Selected Faculty Option");
    homePage.clickProgramDropdown();
    logger.info("Clicked on Program Dropdown");
    homePage.selectProgramOption();
    logger.info("Selected Program");
    homePage.clickBatch();
    logger.info("Clicked on Batch Dropdown");
    homePage.selectBatchOption();
    logger.info("Selected Batch");
    homePage.clickCheckbox();
    logger.info("Checked the Fee Transaction Check Box");
    homePage.UploadTransactionDetails();
    logger.info("Uploaded Fee Transactions");
    homePage.clickAddButton();
    logger.info("Clicked on Add Button");
    homePage.clickYesInPopUp();
    logger.info("Clicked on Yes in the PopUp");
  }
  //@Test(priority = 25,description = "Verifying Navigation Links")
  public void VguTest24() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.studentEmailID();
    logger.info("Entered Email Address");
    homePage.studentPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login");
    homePage.clickOnDashboard();
    logger.info("Clicked on Dashboard");
    homePage.clickOnChat();
    logger.info("Clicked on Chat");
    homePage.clickOnAnnouncements();
    logger.info("Clicked on Announcement");
    homePage.clickOnExamination();
    logger.info("Clicked on Examination");
    homePage.clickOnStudentGradeReport();
    logger.info("Clicked on Grade Report");
    homePage.clickOnFees();
    logger.info("Clicked on Fee");
    homePage.clickOnRequests();
    logger.info("Clicked on Requests");
    homePage.clickOnDashboard();
    logger.info("Clicked on Dashboard");
    homePage.clickOnLMSTab();
    logger.info("Clicked on LMS Tab");
    homePage.clickOnVirtualClass();
    logger.info("Clicked on Virtual Class");
    homePage.clickOnStudentCourse();
    logger.info("Clicked on Course");
    homePage.clickOnAssignment();
    logger.info("Clicked on Assignment");
    homePage.clickOnDiscussion();
    logger.info("Clicked on Discussion");
    homePage.clickOnLibrary();
    logger.info("Clicked on Library");

  }
  @Test(priority = 26,description = "Viewing Request")
  public void VguTest25() {
    homePage = new VGUHomePage(driver);
    driver.get(URL);
    logger.info("Entered VGU Home Page");
    homePage.studentEmailID();
    logger.info("Entered Email Address");
    homePage.studentPassword();
    logger.info("Entered Password");
    homePage.clickLogin();
    logger.info("Clicked on Login");
    homePage.clickOnAnnouncements();
    logger.info("Clicked on Announcements");
    homePage.clickAnnouncementViewMoreButton();
    logger.info("Clicked on View More in Announcement Tab");
    homePage.clickBackButton();
    logger.info("Clicked on Back Button");
  }





}


